name: project_lw
description: Web View Video wallpaper.

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=3.0.0"

#dependencies_override:
#  tar: ^0.2.0-nullsafety

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.3
  google_fonts: ^3.0.1
  marquee_text: ^2.0.0
  cupertino_icons: ^1.0.3
  line_awesome_icons:
    path: ../line_awesome_icons_flutter
  tuple: ^2.0.0
  flutter_staggered_grid_view: ^0.6.1
  shared_preferences: ^2.0.6
  uuid: ^3.0.4
  sqflite: ^2.0.0+3
  flutter_vibrate:
    path: ../flutter_vibrate
  lingyun_widget:
    path: ../lingyun_widget
  es_compression: ^2.0.3
  archive: ^3.1.2
  file_utils: ^1.0.1
  path_provider: ^2.0.2
  package_info: ^2.0.2
  file_picker: ^4.0.0
  permission_handler: ^9.2.0
  share_plus: ^4.0.8
  flutter_ffmpeg: ^0.4.2
  filesystem_picker: ^2.0.1
  another_flushbar: ^1.10.29

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
   - assets/
#   - assets/images/